const SET_USER_INFO = 'SET_USER_INFO'
const SET_COMMENT_LIST = 'SET_COMMENT_LIST'
const SET_MSG_LIST = 'SET_MSG_LIST'
const SET_CHAT_LIST = 'SET_CHAT_LIST'
const SET_UNREAD = 'SET_UNREAD'
const SET_USERS = 'SET_USERS'
const SET_TITLE = 'SET_TITLE'
const SET_SOCKET_ID = 'SET_SOCKET_ID'
const SET_USER_ID = 'SET_USER_ID'
const SET_SOCKET = 'SET_SOCKET'
const SET_USER_AVATAR = 'SET_USER_AVATAR'

export {
  SET_USER_INFO,
  SET_COMMENT_LIST,
  SET_MSG_LIST,
  SET_CHAT_LIST,
  SET_UNREAD,
  SET_USERS,
  SET_TITLE,
  SET_SOCKET_ID,
  SET_USER_ID,
  SET_SOCKET,
  SET_USER_AVATAR
}
